### ISSUE TITLE
Main.java v0.1 생성 및 관리 관련 제안사항

### ISSUE THREAD

**Issue by linkann** [JeongHyeLee/SoftwareEngineering#3]
저번 #HW1 때의 design specification을 생각하며 나름 작성해 본 Main.java(version 0.1)를 올렸습니다.
`
		
		/*----------Variables----------*/
		int mainMenuSelect;
		boolean mainIsWork = true;
		/*-----------------------------*/
		
		/*----------Constructor----------*/
		ToDoList ToDoList = new ToDoList();
		/*-----------------------------*/
`
위와 같이 간단한 가이드라인(?) 몇 개를 주석으로 달아봤는데, 더 좋은 의견 있다면 언제든 반영해주세요!

그리고 Main.java 업데이트 했을 경우, 메시지 commit에 version을 덧붙이면 좋을 것 같아 한 번 덧붙여봤는데, 의견 궁금합니당.^.^!  (예 : v0.1 -> v0.2 -> ... -> v1.0 -> ...)

**Comment by JeongHyeLee** [comment]
각자 기능구현하고나서 업데이트 하면 소수점 자리만 바꾸고 
4명 다 푸쉬한게 돌아가면 일의자리 숫자 바꾸도록 해보는건 어떨까?

**Comment by linkann** [comment]
오홍..그래! 그렇게 하면 더 의미 생기는 거 같아서 좋다!

**Comment by linkann** [comment]
version 관리 issue 결론 : 

1. 개개인의 업데이트 시 -> 소수점 자리 가산 (예: v0.1 v0.2 v0.3 ...)

2. 총 4개의 자바파일(Contacts, Requirement, ToDoList, Note)과 함께 디버깅 했을 때 문제 없는 경우 -> 일의 자리 가산 (예: v1.0 v2.0 v3.0 ...)

_(issue close!)_
